/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.mycompany.poe;

/**
 *
 * @author dini
 */
public class AddFeatures_Task2 {

//Constants
private final int MAX_DESCRIPTION = 50;
private final String[] TASK_STATUS = {"To Do", "Done", "Doing"}; 
//ttracks tasks added
// helps in creating ID

private static int incrTask= 0; 
//Total task duration

private static int totalTaskDuration = 0;  
// Every task added -1

//Class Variables
private int taskNum = 0;  // assigned for static  incrTask
private String taskName = ""; // from user input
private String taskDesc = ""; // from user input
private String devDet = "";  // from user input
private int taskDur = 0;  //  from user input
private String taskID = ""; // autogenerated
private String taskStatus = "";//description of task


public String createTaskID(String taskName, int taskIncr, String devName)
{
    //  first 2 characters from taskname
    String temp = taskName.substring(0,2); 
   
    // add the right format and tasknumber
    temp = temp + ":" + taskIncr + ":";
    //  last 3 characters from developer name
    temp = temp + devName.substring(((devName.length()) - 3));
    // change to all in CAPS
    return temp.toUpperCase();
}





public boolean checkTaskDescription(String description ){
  //use boolean to get true or false value 
    boolean checkTaskDescription = false;
    if (description.length() <= MAX_DESCRIPTION){
        checkTaskDescription = true;
    }
    System.out.println(checkTaskDescription);
     return checkTaskDescription;   
    
}

public String printTaskDetails(){
    
       
    String returnstring = this.taskName + " " + this.taskNum + " " + this.taskDesc + " " +
        this.devDet + " " + this.taskID + " " + this.taskStatus;
       return returnstring;       
    
}

public int TotalTime(){
    //returns total duration of all tasks
    return AddFeatures_Task2.totalTaskDuration;
}

//Custom Methods
public void setTaskDur(int taskDur) {
        this.taskDur = taskDur;
        AddFeatures_Task2.totalTaskDuration = AddFeatures_Task2.totalTaskDuration + taskDur;
    }

//pass the following to num before
public void setTaskStatus(int status) {
        this.taskStatus = TASK_STATUS[status];
        
    }

 public void setTaskNum() {
     // starts at 0
        this.taskNum = AddFeatures_Task2.incrTask;
        // add 1 for the next task
        AddFeatures_Task2.incrTask++; 
    }

//Getters for static varaibles

    public static int getIncrTask() {
        return incrTask;
    }

    public static int getTotalTaskDuration() {
        return totalTaskDuration;
    }


// Getters and Setters for standard variables
    public int getTaskNum() {
        return taskNum;
    }

   

    public String getTaskName() {
        return taskName;
    }

    public void setTaskName(String taskName) {
        this.taskName = taskName;
    }

    public String getTaskDesc() {
        return taskDesc;
    }

    public void setTaskDesc(String taskDesc) {
        this.taskDesc = taskDesc;
    }

    public String getDevDet() {
        return devDet;
    }

    public void setDevDet(String devDet) {
        this.devDet = devDet;
    }

    public int getTaskDur() {
        return taskDur;
    }

    

    public String getTaskID() {
        return taskID;
    }

    public void setTaskID(String taskID) {
        this.taskID = taskID;
    }

    public String getTaskStatus() {
        return taskStatus;
    }

    
}
    
    
    
    
    
    
   
